# Generated by Django 3.2.6 on 2021-09-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_topmusic'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutUs', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ConturctUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutUs', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='legal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutUs', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TermsAndCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutUs', models.TextField()),
            ],
        ),
    ]
