# Generated by Django 3.2.6 on 2021-09-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20210914_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api', models.CharField(max_length=500)),
                ('count', models.IntegerField(default=30)),
            ],
        ),
    ]
